spring:
  profiles:
    active: local
  redis:
    host: localhost
    port: 6379
    timeout: 6000

  datasource:
    url: jdbc:postgresql://localhost:5432/swarnlinkdb
    username: swarnlinkuser
    password: yourpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: swarnlink_schema  # <--- specify your schema here
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        accessKey: test
        secretKey: test
      stack:
        auto: false
      endpoint:
        sqs: http://localhost:4566   # Connect to LocalStack

cloud:
  aws:
    sqs:
      reminder-queue-name: swarnlink-reminder-notification-queue
      region: us-east-1


jwt:
  issuer: swarnlink
  expiration: 15m
  private-key-file-name: private.pem
  public-key-file-name: public.pem

aws:
  sqs:
    notificationQueue: swarnlink-fcm-notification-queue


reminder:
  days-before-close: 3
  batch : 30

user:
  service:
    url: http://localhost:8080  # Replace with actual service hostname in prod

internal:
  auth:
    token: super-secure-internal-token